---
- name: Stop Grafana
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: grafana

  tasks:
    - name: Stop Grafana container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      register: _stop

    - name: Show status after stop
      ansible.builtin.debug:
        msg: "Grafana stopped successfully"
      when: _stop.changed
