# playbooks/traefik/status.yml
---
- name: Traefik status
  hosts: tresor
  gather_facts: false

  vars:
    status_container: "traefik"
    # Optional: assert these ports exist
    status_expected_ports:
      - "80/tcp"
      - "8081/tcp"

  tasks:
    - import_tasks: "../../roles/traefik/tasks/status.yml"
