---
- name: Stop Tresor Index
  hosts: tresor
  become: true
  gather_facts: false
  tasks:
    - name: Stop Tresor Index containers
      ansible.builtin.include_role:
        name: tresor-index
        tasks_from: stop
