---
- name: Restart Prometheus
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: prometheus

  tasks:
    - name: Restart Prometheus container
      community.docker.docker_container:
        name: "{{ container_name }}"
        restart: true
      register: _restart

    - name: Show status after restart
      ansible.builtin.debug:
        msg: "Prometheus restarted successfully"
      when: _restart.changed
