---
- name: Start Prometheus
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: prometheus

  tasks:
    - name: Ensure Prometheus container is started
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: started
      register: _start

    - name: Show status after start
      ansible.builtin.debug:
        msg: "Prometheus started successfully"
      when: _start.changed
