---
- name: Restart Kiwix
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: kiwix

  tasks:
    - name: Restart Kiwix container
      community.docker.docker_container:
        name: "{{ container_name }}"
        restart: true
      register: _restart

    - name: Show status after restart
      ansible.builtin.debug:
        msg: "Kiwix restarted successfully"
      when: _restart.changed
