---
- name: Stop Kiwix
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: kiwix

  tasks:
    - name: Stop Kiwix container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      register: _stop

    - name: Show status after stop
      ansible.builtin.debug:
        msg: "Kiwix stopped successfully"
      when: _stop.changed
