---
- name: Restart timesyncd
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Reload sshd
  become: true
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Apply ip_forward now
  become: true
  ansible.builtin.command: sysctl -w net.ipv4.ip_forward=1

- name: Restart fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart zramswap
  become: true
  ansible.builtin.service:
    name: zramswap
    state: restarted

- name: Restart journald
  become: true
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Reload sysctl
  become: true
  ansible.builtin.command: sysctl --system
