---
- name: Start Tresor Index database
  community.docker.docker_container:
    name: "{{ tresor_index_db_container_name }}"
    state: started

- name: Start Tresor Index scheduler
  community.docker.docker_container:
    name: "{{ tresor_index_scheduler_container_name }}"
    state: started
