---
- name: Remove Jellyfin Media container
  hosts: prod
  become: true
  tasks:
    - name: Remove Jellyfin Media container
      community.docker.docker_container:
        name: jellyfin-music
        state: absent
        force_kill: true
