---
- name: Stop Jellyfin Media
  hosts: tresor
  become: true
  gather_facts: false

  vars:
    container_name: jellyfin-music

  tasks:
    - name: Stop Jellyfin Media container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      register: _stop

    - name: Show status after stop
      ansible.builtin.debug:
        msg: "Jellyfin Media stopped successfully"
      when: _stop.changed
